### ISSUE TITLE
Entity Movement

### ISSUE THREAD

**Issue by jdngray77** [WheelyCatStudios/torte#2]
*This Epic's Acceptance criteria are not yet frozen*

## Description
The vital framework of operations which lay down the behaviours of entity movement.

Mono-behaviour components are expected to be designed with abstraction in mind, whereby the same movement tools can operate upon any entity, and are not limited to an PC or NPC.
 
## Goals
Once this Epic is concidered a success,
* The player will be able to move the Player Character (PC) 
* Contributors will be able to manage the movement of any given entity
* Contributors will be able to manage the movement of NPC's

 
 
## Acceptance criteria
This Epic will be concidered a success once all user stories under this Epic meet thier acceptence criterium.

### Stories
     
 - [x] #3 : WASD Character movement
 - [x] #4 : PC Movement is halt-able
 - [ ] #5 : PC Speed is controllable
 - [x] #7 : The camera moves with the player
 - [ ] #-5 : As a contributor, i can use the movement tools, such that i can manage any given entity
 - [ ] #-6 : As a contributor, i can use the movement tools to make an entity follow a pre-defined path.
 - [ ] #-7 : As a contributor, i can use the movement tools to make an entity face a cardinal direction, such that thier sprite shows the user which what they're facing.
 - [ ] #-8 As a contributor, i can use the movement tools to make an entity move to a specified tile.
 - [ ] #-9 As a contributor, i can use the movement tools to script a scene, such that any entity can move as a scene actor.
 - [ ]  #-10 As a player, i cannot walk into objects with collision meshes, such that i cannot walk through walls or other obstacles
 - [ ] #-11 As the player, i can use the use the direction of a sprite to know which way an entity is facing.

## Timeline
Sprint 1:
	- [ ]   #3 
	- [ ]   #4
	- [ ]   #7   

Unplanned:  
	- [ ]   #5   
	- [ ]   #-5   
	- [ ]   #-6   
	- [ ]   #-7   
	- [ ]   #-8   
	- [ ]   #-9   
	- [ ]  #-10
 	- [ ]  #-11

## Prioritization / Product value
Success of this epic is vital for the end product:

1) Entity's must be able to move, and movement must be manageable. 
2) The player must be able to move the PC to interact with the game. Without it, the game, as presented, is not feasible.

P1 : Product value is extreme.
