### ISSUE TITLE
Epic : Dialogue System

### ISSUE THREAD

**Issue by atallahhezbor** [WheelyCatStudios/torte#32]
## Description

This Epic covers all issues related to
1. Displaying pages of text representing character dialogue on the screen
2. Triggering the display of that text
3. Having a generic way of inputting character dialogue into the game

## Goals

The player should be able to 
- Clearly view the text at an appropriate font size
- View a given "page" of text for as long as desired
- Proceed to the next page of text on demand

Developers should be able to
- Input a dialogue sequence, separated by some special character

 

## Acceptance criteria / User Stories
Define what acceptance criteria, and list sub stories.

This will be considered complete when a given action (it can be mapped to a keypress/button click for now) can trigger a dialogue menu to appear with the character's name and their line of text. A keypress should further advance the text

### Stories
- [ ] Dialogue UI text boxes - no fancy style for now - name and page of text
- [ ] Dialogue Manager/Trigger - control display of UI elements, pagination
- [ ] Dialogue editor element for bulk insert
 
## Timeline
This can't _fully_ complete until character interaction is done, but until then, dialogue can be tested and triggered via key/button press

## Prioritisation / Product value

This one is high priority for this sprint, as the writing team will start supplying us with dialogue pretty soon.
